rpa-tomorrow/rpa-tomorrow

- README.md
- demo.py
- lib/__init__.py
- lib/automate/__init__.py
- lib/automate/modules/__init__.py
- lib/automate/modules/send.py
- lib/settings.py
- substorm-nlp.yml
Modules are listed inside lib/automate/modules. Modules are
required to have the attribute self.verbs and the methods
self.run(self, to, when, body, sender) as well as
self.followup(self, answer). An example module is shown in
lib/automate/modules/send.py, which sends a mail given the
parameters.
The when-parameter is currently ignored, but should
in the future be a datetime.datetime object which defines when the
command should be executed.
The example does not use the self.followup(self, answer). The
intended use of this is to ask extra questions if something in
the original call was unclear.
> Adds API for automation modules

- demo.py
- lib/automate/modules/send.py
- lib/cli/commands.py
- lib/nlp/nlp.py
This PR adds a simple NLP between the CLI and Automation which looks for synonyms to "send", a body of text within single quotation marks and any email addresses. It does not support sending emails to just a contact name, you will need to specify the addresses.
You can test it by starting the SMTP server
```
$ python -m smtpd -n -c DebuggingServer localhost:1025
```
then the CLI, type any sentence with "send" (or synonym) and at least one email. E.g:
```
$ python lib/cli/cli.py
please send an email with the content 'hello world' to substorm@email.com
...
```
Or just run 
```
$ python demo.py
```
Fixes #19
> Add simple NLP for sending emails

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/pull-request-.md
Add issue templates for the project. Makes it easier to add issues etc. as they should show up whenever you add an issue or make a PR.
> Add issue templates

- README.md
- requirements-dev.txt
The dev dependencies can now be installed after activating the conda env
using
```bash
pip install -r requirements-dev.txt
```
currently this install black, flake8 and pytest. We should extend `requirements-dev.txt` with dependencies only needed for development.
> Add dev dependencies

- .github/workflows/python-package-conda.yml
- README.md
- lib/nlp/nlp.py
- requirements-dev.txt
- substorm-nlp.yml
This pull-request reverts having to use pip install -r requirements-dev.txt to install the dev-dependencies.
All dependencies are now installed using conda. The main reason behind
this is that if you install a package using pip inside the conda env and
then you export it to the substorm-nlp.yml file the installed pip
dependencies will be added anyway.
Note that any Pip dependencies can be installed (and added to the env) using `pip install
<name>` and once you update the env file with `conda env export >
substorm-nlp.yml` the pip dependency will be added.
I also added radicale, which is used to start a local CalDav server, as a dependency so you don't have to install it manually when you want to try it locally.
Closes #46
> Move dev dependencies from pip to conda

- .coveragerc
- README.md
- pytest.ini
- substorm-nlp.yml
- tests/test_active.py
- tests/test_example.py
Running pytest will now automatically generate a coverage report which
will be saves as html and can be viewed in `htmlcov/index.html`
> Add pytest config

- lib/__init__.py
- lib/automate/__init__.py
- lib/automate/modules/reminder.py
- lib/cli/commands.py
- reminder_demo.py
- tests/automate/modules/reminder/conftest.py
- tests/automate/modules/reminder/test_notify.py
- tests/automate/modules/reminder/test_run.py
- tests/conftest.py
Implemented a reminder automation module which given a time and body
will schedule a reminder which will pop-up in the users OS. Currently
only Linux is supported and this will have to be extended to also work
on Windows 10 in the future. This can easily be done by adding code to
`Reminder.notify` which invokes something in the windows system that can
create a notification and adding `win32` to the `supported_os[]`. For Linux
I use the notify-send package which is supposed to be bundled with most
Linux distros.
Reminer.run will raise an error if the time at which the reminder is
supposed to happen has already passed or if the function is called from
a host OS that is not currently supported.
To test this you can run `reminder_demo.py`. The demo is currently not
using the NLP module since …
> Add Reminder automation module

- lib/automate/modules/schedule.py
Checks if the sender or recipients are busy during a prospective meeting. If so, it double-checks whether to really book the meeting.
Users without a public Google Calendar are ignored.
Resolves #23
> Check if users are busy when an event is created.

- README.md
- lib/automate/modules/reminder.py
- lib/automate/modules/schedule.py
- lib/automate/modules/send.py
- lib/cli/cli.py
This PR adds a debug flag to the CLI. When enabled it will output debug logs to the terminal output.
Usage:
```
python lib/cli/cli.py -d
```
It also adds debug logging in the NLP parts of each module.
Solves (partially) both #85 and #86
> Add debug flag to CLI

- substorm.sh
Noticed an problem with the if conditions of the setup script which caused the script to not install any models even if no models were installed I also fixed an parse error with the first if statement.
Closes #88
Added missing spacy model `en_core_web_md` to the setup script.
Closes #92 
There is still an issue with this script since as long as at least one model is installed any missing models will not be installed.
> Fix setup script if conditions and add missing spacy model

- lib/automate/modules/schedule.py
This should fix the warning appearing when a calendar event is created. I don't think cache_discovery is needed for what we are doing.
> Disable cache_discovery when building calendar event

- config/contacts.yaml
- lib/automate/modules/schedule.py
- lib/automate/modules/send.py
- lib/settings.py
- lib/utils/contacts.py
- lib/utils/email.py
- tests/automate/modules/send/test_email.py
- tests/utils/conftest.py
- tests/utils/contacts/test_get_emails.py
- tests/utils/email/test_is_email.py
* Created a `utils/` directory and moved existing `is_email()` from Schedule module to this folder to allow for reusability
* Updated the email Regex to also consider emails written in uppercase to be valid (had an issue with this and thought my code was incorrect for a while :P)
- Created a new util function which is able to resolve the email addresses of local contacts given their names (or valid emails directly). This is done by returning a dictionary containing:
- emails: the known emails resolved (if input is a valid email they will automatically be added to emails)
- uncertain: the name and potential candidates and their emails, will contain any contacts which could not be resolved i.e. multiple with same name
- unknown: the input names which could not be resolved to any local …
> Improve the resolving of email addresses given contact names

- lib/cli/cli.py
- lib/cli/commands.py
- lib/cli/config.py
- lib/settings.py
* Decouple cli from settings, to make it possible for the GUI to reuse the settings code.
closes #111
> Decouple cli from settings

- lib/cli/cli.py
* Adds a `--verbose` flag for INFO logging output
* Changes the `--debug` flag to an option instead which requires the debug level output. E.g. `--debug DEBUG`
Fixes #85
> Add variable debug option to CLI

- lib/automate/google.py
* Use the utc converter created by @Blinningjr for the start and end time of a meeting 
- [ x] Schedule a meeting at a specific time and the time in the google calendar should be the same as specified (not -1 hr)
This was fixed by @Blinningjr in PR #103 but when we moved the event to `google.py` the usage of the new function was not included. This just reverts that change.
> Convert time to UTC when scheduling event

- config/contacts.yaml
- examples/remove_schedule_demo.py
- examples/schedule_demo.py
- lib/automate/__init__.py
- lib/automate/google.py
- lib/automate/modules/remove_schedule.py
- remove_schedule_demo.py
* Add a automation module for removing calendar event
* Remove events based on timestamp, participants or event name
* This module is using the Schedule meeting NLP Model, 
* this one does not seem to parse the body though and needs to be looked over
Closes #69
> Remove Calendar Events

- config/nlp_models.yaml
- lib/automate/__init__.py
- lib/automate/modules/__init__.py
- lib/automate/modules/reminder.py
- lib/automate/modules/remove_schedule.py
- lib/automate/modules/schedule.py
- lib/automate/modules/send.py
- lib/automate/pool.py
- lib/utils/contacts.py
- lib/utils/ner.py
- substorm-nlp.yml
- substorm.sh
- tests/automate/modules/reminder/conftest.py
- tests/automate/modules/send/conftest.py
- tests/utils/contacts/test_get_emails.py
* Modules will only be initialized once
* Program will be quicker but might require more memory as modules now stay loaded in memory until program is exited
* From my own testing it initially required more memory at start but then stayed at the same size unlike the current design where the memory stack keeps growing during use.
* All verbs/keywords now correspond to a single object instead of a module object for each keyword
* Modules now have access to a shared NLP model pool
* For NLP models that are used or will be used by many automation modules
* Keeps memory usage lower as they are shared and only needs to load once
* Name Entity Recognition utilities added, to be able to parse full names from text
* Only implemented in `send` module but followup still happens (bug?)
Please describe …
> Add full name parsing utilities and improve module/model initialization

- .gitignore
- README.md
- lib/__init__.py
- lib/cli/commands.py
- lib/cli/helpprompt.txt
- lib/speech/microphone.py
- lib/speech/transcribe.py
- substorm-nlp-win.yml
- substorm-nlp.yml
- tests/speech/conftest.py
- tests/speech/test_transcribe.py
* Adds functionality for reading a continuous stream of microphone input 
* Adds a function which will use the Google Cloud Speech-to-Text API to transcribe one sentence (until the user stops speaking for a certain time) and returns the interpreted text
* Adds an `r` or `record` command to the CLI which will ask the user to instruct the computer using voice. This is basically the same as the original text input just that the voice is transcribed to text before invoking the NLP module. The user is asked to confirm that the transcribed text is correct before the task is executed.
Please check out [this](https://github.com/rpa-tomorrow/substorm-nlp/blob/127-stt-layer/README.md#google-service-account) README section for how to setup a service account which is needed for the Speech-to-Text API …
> Add a Speech-to-Text layer which makes it possible for the user to instruct the program using voice

- lib/selector/selector.py
* Add more chars to the input whitelist such that email and time parsing is possible again
* Remove something-copied-from-stack-without-hesistation regex expression to remove last punctuation, now use Python built in rstrip instead
These did not work previously
- `remind me at 16:00 to go out`
- `send an email to john@email.com`
These worked before (and now too)
- `remind me in 5 seconds to eat`
- `send an email to John Doe`
Fixes #150, fixes #151
> Add chars to input WL and remove bad regex

- .flake8
- .github/workflows/python-package-conda.yml
- lib/cli/cli.py
- lib/cli/commands.py
- lib/cli/spinner.py
- lib/selector/selector.py
- substorm-nlp.yml
Major
* Change CLI library from `plac` to `click` which supports a lot more features and works flawlessly on Windows
* Add some color output
* Give user some helpful instructions after loading models is finished
Minor
* Rename `nlp` to `selector` in CLI code
* Add pep8-naming plugin to check naming conventions with flake8 (helpful but optional!)
* Ignore naming convention on Github workflows checks as it is optional
With `python lib/cli/cli.py`
- Tested and displays correctly on both Linux and Windows
n/a
> Change CLI library and make CLI more intuitive

- lib/automate/google.py
- lib/automate/modules/remove_schedule.py
* Fix removal of meetings by both timestamp and summary
- Create a meeting at a time during the current hour, if it is 10:20 then create a meeting at 10:30
- input `remove meeting at 10:30`, you should be prompted about removing the newly created meeting
- Create  a meeting with a summary `test`
- input `remove meeting about test`, you should be prompted about removing the newly created meeting
Fixes #156
> 156 remove meeting

- .github/workflows/python-package-conda.yml
- substorm-nlp.yml
- tests/conftest.py
- tests/selector/conftest.py
- tests/selector/test_prepare.py
- tests/selector/test_selector_run.py
- tests/selector/use_cases/conftest.py
- tests/selector/use_cases/test_remove_schedule.py
- tests/selector/use_cases/test_schedule.py
- tests/selector/use_cases/test_send_email.py
- Added tests for the selector. These tests try to confirm that our module
selector can, given certain input, select each of our models.
- Added tests for use cases send email, schedule meeting and remove
meeting. These tests do not test any followup logic only checks that the
use case can be executed with our current models etc.
Hopefully this will help us detect some regression in the future.
- pytest
Fixes #160
> Add selector and use case tests

- lib/automate/modules/send.py
- lib/automate/pool.py
- tests/automate/pool/conftest.py
- tests/automate/pool/test_pool.py
- tests/automate/pool/test_sharedmodel.py
* New data structure `SharedModel` that wraps around a spacy model together with a mutex lock
* `SharedModels` can be fetched from the `ModelPool`
* When using a spacy model from `SharedModel` it will be automatically locked/unlocked
* Example usage:
```python
m = ModelPool(["en_core_web_sm"])
s = m.get_shared_model("en_core_web_sm")
with s:
spacy_model = s.acquire_model()
```
Unit test:
- First use SharedModel on one thread, then try to use it on another thread (should block)
- First use SharedModel on one thread, finish job, then try to use it on another thread (should access immediately)
Manual testing:
- Add prints id of the models accessed inside `send` module and check that …
> Simplify ModelPool usage and automatically lock/unlock lock

- lib/automate/modules/remove_schedule.py
- lib/automate/modules/schedule.py
- lib/automate/modules/update_schedule.py
- lib/cli/cli.py
- lib/cli/commands.py
- requirements.txt
- tests/selector/use_cases/conftest.py
* Catch KeyboardInterrupts from the modules and then continue the program. Lets one abort the task during preparation.
* Fix invalid ModelPool usage in the schedule modules
* Fixes unit tests for removing calendar (cred @hugowangler)
- Prepare an incomplete task, then abort with either `C-c` or `C-d`. Should return to the main program again.
Fixes #155, fixes #171
> Catch program aborts when preparing tasks, fix invalid ModelPool usage

- lib/automate/__init__.py
- lib/automate/followup.py
- lib/automate/modules/reminder.py
- lib/automate/modules/remove_schedule.py
- lib/automate/modules/schedule.py
- lib/automate/modules/send.py
- lib/automate/modules/update_schedule.py
- lib/utils/contacts.py
- lib/utils/ner.py
Earlier the followup was handled by the automation modules
themselves, returing only a string for context.
This commit defines a Followup interface, with inherited classes
MultiFollowup, StringFollowup and BooleanFollowup. The attributes
of the different classes differ somewhat, but they all contain
a .question and an .answer. Control can be given back to the
automation module via a .callback().
* Move all print() and input() to the CLI.
* Use classes to return instead of strings when doing followup questions.
- Ran all followup questions in all four modules in the CLI. Some were hard to reach, so I did some temporary patching to reach those.
Fixes #158
> Creates a followup object

- src/main/python/design_view.py
- src/main/python/main.py
* `send an email to John Doe. remind me in 10 seconds` now generates two processes in the GUI
* Each block can also be edited individually, the query is essentially split by `.` and given to each block.
- Test that the query given above produces first one send block connected to a reminder block.
Fixes #148
> 148 gui mutlitask

- lib/utils/contacts.py
* Correctly update the `to` attribute of the schedule module when the user is prompted to confirm single contact followup
This was actually not a problem with Google contacts, I think we just forgot to test how we handle single candidate followups after the followup improvements. IIRC this only occurs when the specified contact is a google contact since we will automatically resolve the contact if it only has a single match in the local contact book.
- using input: `schedule a meeting with <Name of google contact with unique name> at 17:00 about test1337`
Fixes #180
> Fix single contact followup

- config/editor.yaml
- src/main/python/main.py
- src/main/python/settings_view.py
- src/main/qss/base.qss
- Added all of the settings required to use the program
- Added validation to most of the settings fields, this includes
- Editor
- font-size: Not empty and only numbers allowed
- Meetings
- standard duration: Not empty and only numbers allowed
- User
- name: Not empty
- email: Not empty and only valid emails allowed
- Added red outline to any invalid fields which will be updated every time the input is changed
- Added restore and update buttons
- Restore will revert all fields to the initial settings.
- Update will update the settings in the different config files. This will not be done if anything is invalid/missing.
Also, the password field will not show the password (dots). The user is
also only allowed to select the model languages and versions
defined in `./config/nlp_models.yaml`. …
> Add missing settings and validation of fields to GUI

- lib/automate/modules/reminder.py
- lib/automate/modules/remove_schedule.py
- lib/automate/modules/schedule.py
- lib/automate/modules/send.py
- lib/automate/modules/update_schedule.py
- lib/selector/selector.py
- lib/utils/contacts.py
- tests/selector/conftest.py
- tests/selector/use_cases/conftest.py
* Before executing a task the user gets prompted with a small description of what task has been processed
* The user gets to choose if the task should be executed or aborted
* Because a Reminder is a small local task that does not carry any side effects in case something is processed wrong it does not require a prompt 
* Update unit tests to accommodate these changes
- Run the CLI, try out each of the modules
- Send email and create/remove calendar should prompt before execution
- Reminders should not prompt before execution
Fixes #159
> Prompt the user before executing task

- lib/automate/modules/schedule.py
* Remove the user as a guest participant of its own event
- schedule an event with a participant, check in the calendar that the intended participant is the only guest participant in the event 
Fixes #184
> Remove the user from being a guest participant in its own event

- README.md
- docs/accepted_input.md
- docs/debug_options.md
- docs/google_auth_setup.md
- requirements.txt
- substorm.sh
* Move detailed information to `docs/` instead
* Simplify certain parts so it is easier to get an overview of the project
* Add a CLI demo and badges and other unnecessary but cool things
Minor things:
- Update requirements such that the official spacy models not found on conda repos are included there instead of inside the substorm.sh script
- I read the README.md twice
Fixes #162
> Cleanup the README

- lib/utils/ner.py
- tests/utils/ner/test_cross_check.py
* When comparing our models' tagged names with spacy's recognized names, our cross checker will append the missing tags if they are not found in the recognized names list
- Implemented unit tests for the weird cases names are not found
- Try to send an email to `Mark` and check with debug output that `mark` is a recipient
Fixes #196
>  Fix NER bug where certain names are seen as words

- lib/utils/contacts.py
* When there is only one contact the user has to confirm e.g. a google
contact found, the users answer to Y/n will now be taken into account
and not use the contact if the answer is no.
- send an email to GOOGLE CONTACT, respond with no should remove the contact as a recepient
- same but with schedule
- same as the above tests but responding with yes should add them as a receiver 
Fixes #198
> Fix handling of answer on single contact followup

- .github/workflows/python-package-conda.yml
- README.md
- docs/google_auth_setup.md
- init_env.sh
- rpa-tomorrow-win.yml
- rpa-tomorrow.yml
* Rename all occurrences of `substorm-nlp` to `rpa-tomorrow`
* Will rename on Github if this PR is approved
- Create a new environment with the new name (e.g. run the init file)
Fixes #204
> Rename substorm-nlp to rpa-tomorrow

- lib/automate/google.py
- lib/automate/modules/schedule.py
* Changed the return method of the freebusy query result
* Adjusted the timezone of the queries to the systems local timezone
- Should be able to inform you the user that they are busy when scheduling a meeting 
Fixes #143
> Fix freebusy return value
